"""Prompts → markdown, and the machine-readable index beside it.

House style is indexia's `recent/*.md`: a title, an italic provenance line saying what
generated the file and when it is overwritten, then sections. A run that finds nothing says
*why* — "quiet" and "broken" look identical in an empty file, and only one is your problem.

Prompts are **numbered**, and the numbers are the interface: `scripts/write.sh 3` opens a
session on prompt 3 in whichever project it belongs to. That is why `index()` exists — the
markdown is for you, the JSON is for the tooling, and neither is parsed from the other.

**Sections are the sources, in `SOURCES` order**: your notes, then your writing, then your
reading. It used to be short-form/long-form at the top, which read as a run sorted by shape
and put a note about someone else's paper above an essay your own corpus is owed. Length has
not gone — it is the count in the summary line, and it still orders prompts inside a source
— but it is no longer the thing you see first.

Both `render()` and `index()` order by `Prompt.rank` themselves rather than trusting the
caller. They have to agree exactly: `index()` assigns the numbers, `render()` prints them,
and `scripts/write.sh 3` is wrong the moment those two disagree about what 3 is.
"""
from datetime import datetime, timezone

from .signals import LENGTH

HEADINGS = {
    "note": "Notes — one claim, standing alone",
    "verse": "Verse",
    "essay": "Essays — longer, argued",
    "journal": "Journal — dated, personal",
}
SOURCE_HEADINGS = {
    "indexia": "From your notes — indexia",
    "perceptua": "From your writing — perceptua",
    "arxiv": "From your reading — arxiv",
}


def _ordered(prompts):
    return sorted(prompts, key=lambda p: p.rank)


def index(prompts):
    """The addressable form of a run: [{n, register, project, ask, …}]."""
    return [{
        "n": n,
        "register": p.register,
        "length": p.length,
        "form": p.form,
        "project": p.project,
        "ask": p.ask,
        "because": p.because,
        "title": p.signal.title,
        "ref": p.signal.ref,
        "source": p.signal.source,
        "detail": p.signal.detail,
        "commit": p.commit,
    } for n, p in enumerate(_ordered(prompts), 1)]


def render(prompts, stats=None):
    stats = stats or {}
    now = datetime.now(timezone.utc)
    L = [f"# Elicitations — {now.strftime('%Y-%m-%d')}", ""]
    L += ["_Generated by `scripts/elicit.sh`; overwritten on each run. Every prompt names a "
          "site and a shape and stops there — what it is about is yours. eliciter reads "
          "indexia and perceptua through a read-only gate and writes to neither; "
          "`scripts/write.sh <n>` opens a session where the writing belongs._", ""]

    counts = stats.get("sources") or {}
    if counts:
        L += ["_Sources: " + " · ".join(f"**{k}** {v}" for k, v in counts.items()) + "._", ""]

    if prompts:
        # The short/long split used to be the top-level structure; this line is what is left
        # of it, and it answers the same question — have I got a short thing and a long
        # thing today — without deciding the order of the whole run.
        n_short = sum(1 for p in prompts if p.length == "short")
        L += [f"_{n_short} short · {len(prompts) - n_short} long._", ""]

    if not prompts:
        L += ["## Nothing to ask", "",
              stats.get("quiet") or
              "No source produced a signal. That is a real answer — the queue is clear, "
              "the corpus is settled, and nothing is owed.", ""]
        return "\n".join(L)

    # Walk the run in rank order and open a section whenever the source changes, a
    # subsection whenever the register does. Filtering into nested groups instead — the old
    # shape — lets the printed order drift from `rank` the next time either changes; here
    # they are the same walk, so they cannot.
    src = reg = None
    for n, p in enumerate(_ordered(prompts), 1):
        if p.signal.source != src:
            src, reg = p.signal.source, None
            L += [f"## {SOURCE_HEADINGS.get(src, src)}", ""]
        if p.register != reg:
            reg = p.register
            L += [f"### {HEADINGS.get(reg, reg.title())}", ""]
        L += [f"#### {n}. {p.signal.title}", "", f"**{p.ask}**", ""]
        if p.because:
            L += [p.because, ""]
        if p.signal.detail:
            L += ["<details><summary>the material</summary>", "",
                  _quote(p.signal.detail), "", "</details>", ""]
        meta = [f"`{p.form}`", LENGTH.get(p.register, "short")]
        if p.signal.ref:
            meta.append(f"from `{p.signal.ref}`")
        L += ["— " + " · ".join(meta), ""]
        if p.commit:
            L += [f"→ {p.commit}", ""]
        L += [f"→ `bash scripts/write.sh {n}` to write it in {p.project}", ""]
    return "\n".join(L)


def _quote(text):
    """Blockquote a block, keeping blank lines inside it part of the quote. A bare blank
    line would end the quote and dump the rest of a poem into the page body."""
    return "\n".join(f"> {ln}" if ln.strip() else ">" for ln in text.splitlines())
